name: GitHub Actions course
on: [push]
jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Define var
        run: echo "USERNAME=${{ github.actor }}" >> $GITHUB_ENV
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.8.1
        with:
          node-version: 16.18.1
      - name: Run JS script
        run: node console.js
